GH-26727: [C++][Flight] Use ipc::RecordBatchWriter with custom IpcPayloadWriter for TransportMessageWriter (DoExchange) (#47410)
### Rationale for this change

The Flight Server DoExchange method currently does not support Dictionary replacement or Dictionary Deltas, similar to how the client currently behaves or how we do for DoGet we should use an `ipc::RecordBatchWriter` with a custom `IpcPayloadWriter` instead of reimplementing Dictionary Replacement / Deltas logic.

### What changes are included in this PR?

Removes manually generation of individual ipc Payloads and uses an `ipc::RecordBatchWriter` and a custom  `TransportMessagePayloadWriter` to modify the `IpcPayloads` into `FlightPayloads`.

### Are these changes tested?

Yes, existing tests cover the DoExchange functionality and new test for Python has been added where Dictionary deltas are being send via DoExchange. The test was failing before this change because the dictionary wasn't updated:
```python
            received_table = reader.read_all()
            expected_table = simple_dicts_table()
>           assert received_table.equals(expected_table)
E           assert False
E            +  where False = equals(pyarrow.Table\nsome_dicts: dictionary<values=string, indices=int64, ordered=0>\n----\nsome_dicts: [  -- dictionary:\n["foo... -- dictionary:\n["foo","baz","quux"]  -- indices:\n[2,1],  -- dictionary:\n["foo","baz","quux","new"]  -- indices:\n[0,3]])
E            +    where equals = pyarrow.Table\nsome_dicts: dictionary<values=string, indices=int64, ordered=0>\n----\nsome_dicts: [  -- dictionary:\n["foo...ull],  -- dictionary:\n["foo","baz","quux"]  -- indices:\n[2,1],  -- dictionary:\n["foo","baz","quux"]  -- indices:\n[0,3]].equals

pyarrow/tests/test_flight.py:2596: AssertionError
================================================================================== short test summary info ===================================================================================
FAILED pyarrow/tests/test_flight.py::test_flight_dictionary_deltas_do_exchange - assert False

```

### Are there any user-facing changes?

No, only that the expected dictionary replacement/deltas will work for DoExchange.

* GitHub Issue: #26727

Authored-by: Raúl Cumplido <raulcumplido@gmail.com>
Signed-off-by: Raúl Cumplido <raulcumplido@gmail.com>